### ISSUE TITLE
flarum已经发布1.0.4、拓展已不支持

### ISSUE THREAD

**Issue by vlssu** [bs-community/flarum-oauth-client#8]
如图，整个改版、使用旧版的插件已完全不支持了，插件的设置页面也完全打不开了
![image](https://user-images.githubusercontent.com/43847794/133209443-e9851be7-303f-4161-adb8-94d81eac9c65.png)

**Comment by g-plane** [comment]
那你为什么不用新版的插件呢？

**Comment by vlssu** [comment]
我在[Blessing Skin 用户手册]文档中没有看见新版插件的文档，可以提供给我吗

**Comment by g-plane** [comment]
就是正常地用 Composer 更新呀。

**Comment by vlssu** [comment]
但。。我是重新搭建重新安装的呀，按理说我直接安装的最新版啊

**Comment by g-plane** [comment]
把你的 `composer.json` 文件贴出来看看。

**Comment by vlssu** [comment]
![image](https://user-images.githubusercontent.com/43847794/133215983-ed09c915-bcad-4e9c-b326-85430613b38c.png)
```
{
    "name": "flarum/flarum",
    "description": "Delightfully simple forum software.",
    "type": "project",
    "keywords": [
        "forum",
        "discussion"
    ],
    "homepage": "https://flarum.org/",
    "license": "MIT",
    "authors": [
        {
            "name": "Flarum",
            "email": "info@flarum.org",
            "homepage": "https://flarum.org/team"
        }
    ],
    "support": {
        "issues": "https://github.com/flarum/core/issues",
        "source": "https://github.com/flarum/flarum",
        "docs": "https://flarum.org/docs/"
    },
    "require": {
        "blessing/flarum-oauth-client": "^2.0",
        "flarum-lang/chinese-simplified": "^1.0",
        "flarum/approval": "*",
        "flarum/bbcode": "*",
        "flarum/core": "^1.0",
        "flarum/emoji": "*",
        "flarum/flags": "*",
        "flarum/lang-english": "*",
        "flarum/likes": "*",
        "flarum/lock": "*",
        "flarum/markdown": "*",
        "flarum/mentions": "*",
        "flarum/nicknames": "*",
        "flarum/pusher": "*",
        "flarum/statistics": "*",
        "flarum/sticky": "*",
        "flarum/subscriptions": "*",
        "flarum/suspend": "*",
        "flarum/tags": "*",
        "fof/best-answer": "^1.1",
        "fof/drafts": "*",
        "fof/links": "^1.0",
        "fof/passport": "^1.0",
        "fof/profile-image-crop": "*",
        "fof/recaptcha": "^1.0",
        "fof/sitemap": "^1.0",
        "fof/split": "*",
        "fof/user-directory": "*"
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}
```

**Comment by g-plane** [comment]
有其它错误信息吗？我现在没有 Flarum 环境，没法进行测试。

**Comment by vlssu** [comment]
这插件安装上去后，设置界面是没有的（也就是我上面发的图）
所以。。。因为没有设置界面无法判断错误信息
日志中没有任何文件

**Comment by g-plane** [comment]
现在暂时只能搁着了……

**Comment by vlssu** [comment]
> 现在暂时只能着急了……

哈哈，没事，哦对了我捐助了

**Comment by Kamijouko** [comment]
坐等插件更新+1....

**Comment by vlssu** [comment]
@g-plane 现在能够正常配置，但依旧无法正常使用，这是我的问题吗
![image](https://user-images.githubusercontent.com/43847794/151929265-1551b509-1ae9-49bd-8e7f-7f49d3157081.png)
![image](https://user-images.githubusercontent.com/43847794/151929317-64a5f33f-4fd8-4344-bcd7-73276345bad3.png)

### flarum日志
```
[2022-02-01 07:36:51] flarum.ERROR: UnexpectedValueException: Invalid response received from Authorization Server. Expected JSON. in /www/wwwroot/bbs.vlssu.cn/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:787
Stack trace:
#0 /www/wwwroot/bbs.vlssu.cn/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(767): League\OAuth2\Client\Provider\AbstractProvider->fetchResourceOwnerDetails()
#1 /www/wwwroot/bbs.vlssu.cn/vendor/blessing/flarum-oauth-client/src/Controllers/PassportController.php(72): League\OAuth2\Client\Provider\AbstractProvider->getResourceOwner()
#2 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Blessing\Flarum\Controllers\PassportController->handle()
#3 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#4 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process()
#5 /www/wwwroot/bbs.vlssu.cn/vendor/fof/oauth/src/Middleware/ErrorHandler.php(50): Laminas\Stratigility\Next->handle()
#6 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\OAuth\Middleware\ErrorHandler->process()
#7 /www/wwwroot/bbs.vlssu.cn/vendor/fof/secure-https/src/Middlewares/ContentSecurityPolicyMiddleware.php(32): Laminas\Stratigility\Next->handle()
#8 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\SecureHttps\Middlewares\ContentSecurityPolicyMiddleware->process()
#9 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#10 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#11 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#12 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#13 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#14 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#15 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#16 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#17 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#18 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process()
#19 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#20 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process()
#21 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#22 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process()
#23 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#24 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process()
#25 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#26 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process()
#27 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#28 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process()
#29 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#30 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CollectGarbage->process()
#31 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#32 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process()
#33 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#34 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process()
#35 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#36 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process()
#37 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#38 /www/wwwroot/bbs.vlssu.cn/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#39 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process()
#40 /www/wwwroot/bbs.vlssu.cn/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#41 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process()
#42 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#43 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process()
#44 /www/wwwroot/bbs.vlssu.cn/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#45 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process()
#46 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#47 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process()
#48 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#49 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#50 /www/wwwroot/bbs.vlssu.cn/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#51 /www/wwwroot/bbs.vlssu.cn/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#52 /www/wwwroot/bbs.vlssu.cn/public/index.php(26): Flarum\Http\Server->listen()
#53 {main}  
```
bs没有日志

**Comment by g-plane** [comment]
v2.0.2 已发布，支持 Flarum 1.2。
